### ISSUE TITLE
my project PRD and Project task list

### ISSUE THREAD

**Issue by Yalalt** [Pinecone-aqua/travelway#293]
- [x]  Determine the UX design
- [x] Build MVP Frontend and back-end
- [x] Develop wireframes and mockups
- [x] Build the back-end
- [x] Build the front-end
- [x] Test components, page and debug
- [x] Deploy and maintain
